obj.BEGIN x, y
obj.END x, y
obj.alias x, y
obj.and x, y
obj.begin x, y
obj.break x, y
obj.case x, y
obj.class x, y
obj.def x, y
obj.defined? x, y
obj.do x, y
obj.else x, y
obj.elsif x, y
obj.end x, y
obj.ensure x, y
obj.false x, y
obj.for x, y
obj.if x, y
obj.in x, y
obj.module x, y
obj.next x, y
obj.nil x, y
obj.not x, y
obj.or x, y
obj.redo x, y
obj.rescue x, y
obj.retry x, y
obj.return x, y
obj.self x, y
obj.super x, y
obj.then x, y
obj.true x, y
obj.undef x, y
obj.unless x, y
obj.until x, y
obj.when x, y
obj.while x, y
obj.yield x, y
obj.__LINE__ x, y
obj.__FILE__ x, y
obj.__ENCODING__ x, y
