f(k => v)
f(k => v,)
f(x, k => v)
f(x, k => v,)
f(*x, k => v)
f(*x, k => v,)
f(x, *y, k => v)
f(x, *y, k => v,)
f(k1 => v1, k2 => v2)
f(k1 => v1, k2 => v2,)
f(x, k1 => v1, k2 => v2)
f(x, k1 => v1, k2 => v2,)
f(*x, k1 => v1, k2 => v2)
f(*x, k1 => v1, k2 => v2,)
f(x, *y, k1 => v1, k2 => v2)
f(x, *y, k1 => v1, k2 => v2,)
